### ISSUE TITLE
Query timed out on latest MC version

### ISSUE THREAD

**Issue by DreamPhreak** [McLive/api.minetools.eu#1]
I see that Query works with your server at: http://api.minetools.eu/query/lobby.freecraft.eu/25555 on version 1.8.8

However when I try to use the same thing with my server, I get "error": "timed out", http://api.minetools.eu/query/mega.pwn9.com/25556 on version 1.9.4

Also I do have query enabled, even said this in console: "[20:29:55] [Query Listener #1/INFO]: Query running on 0.0.0.0:25556"

**Comment by McLive** [comment]
Looks like your firewall is blocking connections to that port as I can't reach it.

> root@srv:~# nc -v -u -z -w 3 mega.pwn9.com 25556
> mega.pwn9.com [74.116.121.34] 25556 (?) : No route to host
