### ISSUE TITLE
500 Server error

### ISSUE THREAD

**Issue by CarbonNeuron** [McLive/api.minetools.eu#10]
Having another server error. I saw the other issue and would like to notify you.

**Comment by CarbonNeuron** [comment]
Update, now its a 503 server issue:
https://gyazo.com/08ebb4dcd59b7bf6a0b49f8d16dab09b

**Comment by McLive** [comment]
Currently looking into it

**Comment by McLive** [comment]
It works again now, still need to check why the redis server couldn't save to disk anymore.
