### ISSUE TITLE
I hope to set up a branch station.

### ISSUE THREAD

**Issue by ghost** [McLive/api.minetools.eu#12]
Request Open Source

In China, your website is blocked by the National Firewall, which makes it impossible to use in some areas. I hope to set up a sub-station/mirror website in China.

My English is very poor. If there are grammatical mistakes, I'm sorry.

**Comment by McLive** [comment]
Hi,

I currently don't plan to open source this. May I know why it is blocked in China?

**Comment by llsg-mc-yhh-10086** [comment]
You should know that there is a firewall system called Great Firewall of China in China. I feel that Google Search can find information about this system. Because this system has many imperfections, it often blockades an IP segment directly, such as spigotMC system, so it needs VPN to access.

**Comment by llsg-mc-yhh-10086** [comment]
> You should know that there is a firewall system called Great Firewall of China in China. I feel that Google Search can find information about this system. Because this system has many imperfections, it often blockades an IP segment directly, such as spigotMC system, so it needs VPN to access.

1

**Comment by ghost** [comment]
> Hi,
> 
> I currently don't plan to open source this. May I know why it is blocked in China?

You should know that there is a firewall system called Great Firewall of China in China. I feel that Google Search can find information about this system. Because this system has many imperfections, it often blockades an IP segment directly, such as spigotMC system, so it needs VPN to access.
