### ISSUE TITLE
uuid null while actual premium account

### ISSUE THREAD

**Issue by xknat** [McLive/api.minetools.eu#15]
![image](https://user-images.githubusercontent.com/10220139/64118031-03432a80-cd97-11e9-89d1-bb99eb2cd58f.png)

**Comment by Fiahblade** [comment]
@xknat Also have this issue but only when I specified an uuid with dashes. Without it always worked.

**Comment by xknat** [comment]
@Fiahblade 
> uuid with dashes

What?

**Comment by Fiahblade** [comment]
853c80ef-3c37-49fd-aa49-938b674adae6
853c80ef3c3749fdaa49938b674adae6

**Comment by McLive** [comment]
Fixed long time ago
