### ISSUE TITLE
Doesn't work with forge servers

### ISSUE THREAD

**Issue by Derkades** [McLive/api.minetools.eu#16]
```json
{
  "error": "expected string or buffer"
}
```

See https://github.com/ServerSelectorX/ServerSelectorX/issues/140

**Comment by McLive** [comment]
I‘ll see if I can add support for that

**Comment by McLive** [comment]
This has been fixed now 

https://api.minetools.eu/ping/play.64stacks.com/25567

**Comment by Derkades** [comment]
That was quick, thank you
