### ISSUE TITLE
query stopped working

### ISSUE THREAD

**Issue by Wepwawetcode** [McLive/api.minetools.eu#18]

**Comment by McLive** [comment]
It works fine for me.. Please provide an ip and port which is not working.

**Comment by Wepwawetcode** [comment]
play.wepwawet.xyz
25565

Verstuurd vanaf mijn iPhone

**Comment by Wepwawetcode** [comment]
first https://api.minetools.eu/query/play.wepwawet.xyz/ this was enough but now I also have to add the port anyway thanks for the help https://api.minetools.eu/query/play.wepwawet.xyz/25565

**Comment by McLive** [comment]
Both works for me but I'm glad it's solved now. :)
