### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by CarbonNeuron** [McLive/api.minetools.eu#20]
Getting no response from the server

**Comment by CarbonNeuron** [comment]
The domain looks to be unregistered now.
It says Unfortunately we do not know this domain.
If it belongs to you, you can add the domain to your Uberspace as described in the wiki.

**Comment by CarbonNeuron** [comment]
Server is offline

**Comment by Sitmobedaf** [comment]
Confirm

**Comment by CarbonNeuron** [comment]
I found an API that's hosted by steam or some other company that seems to be working great! Returns even more info. https://playerdb.co/ If you were looking at a solution to these outages

**Comment by McLive** [comment]
Sorry, I'm trying to figure out why the whole host keeps crashing these days...

**Comment by McLive** [comment]
Up again
