### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by MrTalon63** [McLive/api.minetools.eu#24]
I'm getting this error message, but server is online

{
  "error": "ord() expected a character, but string of length 0 found"
}

**Comment by McLive** [comment]
Can you please send me an URL where this happens?

**Comment by MrTalon63** [comment]
https://api.minetools.eu/ping/116.202.173.86/21648

**Comment by McLive** [comment]
Looks like it works now. Not sure what happened there.

![image](https://user-images.githubusercontent.com/5620071/82354598-4e729b80-9a01-11ea-81da-00035f854ef7.png)
