### ISSUE TITLE
API constantly down?

### ISSUE THREAD

**Issue by vastolf** [McLive/api.minetools.eu#27]
I keep trying to make requests to: 

And I get the following response:
```
{
  "error": "timed out", 
  "status": "ERR"
}
```

I use your API for my website, have for a week or so (usually works great but for past day or so it's been mostly down).

Same thing happens when I try another server IP:

**Comment by vastolf** [comment]
But for some reason this server works?

**Comment by McLive** [comment]
Looks like minetools can't connect to your server. Are you sure you allow connections to that port?

**Comment by McLive** [comment]
Actually, I can't connect. ``netheranarchy.org [147.135.104.5] 23598 (?) : Connection refused``

**Comment by vastolf** [comment]
It works for a while and then stops working all of the sudden

server.properties:

```
query.port=23598
```

**Comment by vastolf** [comment]
@McLive and other sites like Planet Minecraft connect to me fine:

**Comment by McLive** [comment]
I don't know how the other sites work but I guess they use the ping protocol.

I still can't reach your server. 
`netheranarchy.org [147.135.104.5] 23598 (?) : Connection refused`

**Comment by vastolf** [comment]
@McLive it was working for about 5 days and suddenly stopped working. Any setting I can change potentially to fix this?

**Comment by McLive** [comment]
@vastolf I have no idea, sorry. Nothing changed on minetools. Maybe your firewall is blocking connections to that port.
