### ISSUE TITLE
Minecraft MODPACK SERVER issue

### ISSUE THREAD

**Issue by LuffyCraftingDead** [McLive/api.minetools.eu#28]
If i use the API in minecraft server from Crafting Dead (A MOD from Technic) has error. Put the modpack (and others modpacks servers) in the api, please.

**Comment by McLive** [comment]
Please supply more information. 
- Ping or query API
- Exmaple IP and port

**Comment by LuffyCraftingDead** [comment]
IP: originsurvival.ecxon.com.br
API: https://api.minetools.eu/ping/189.127.164.65

>
