### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Gary520** [McLive/api.minetools.eu#3]
Some nicknames with 15 characters causes timeout.

Exemple:
https://api.minetools.eu/uuid/montmaxdanstonq
https://api.minetools.eu/uuid/Turkish_Sinan61
https://api.minetools.eu/uuid/xXcrafter2211Xx

**Comment by McLive** [comment]
There was a bug with redis not releasing locks properly. Thats now fixed.

Thanks for reporting. :)
