### ISSUE TITLE
Status err id null?

### ISSUE THREAD

**Issue by xhmr** [McLive/api.minetools.eu#32]
For some nicknames api is not working since yesterday, for example:
https://api.minetools.eu/uuid/123456xd
```
{
  "cache": {
    "HIT": false, 
    "cache_time": 86400, 
    "cache_time_left": 86399, 
    "cached_at": 1602295181.776628, 
    "cached_until": 1602381581.776628
  }, 
  "id": null, 
  "name": "123456xd", 
  "status": "ERR"
}
```

**Comment by McLive** [comment]
That user doesn't exist since mojang returns no UUID for it. 

https://api.mojang.com/users/profiles/minecraft/123456xd

**Comment by xhmr** [comment]
@McLive it doesn't work for some premium users too.

**Comment by xhmr** [comment]
@McLive https://api.minetools.eu/uuid/MamFuu
`{
  "cache": {
    "HIT": true, 
    "cache_time": 86400, 
    "cache_time_left": 7669, 
    "cached_at": 1602258472.900983, 
    "cached_until": 1602344872.900983
  }, 
  "id": null, 
  "name": "mamfuu", 
  "status": "ERR"
}`
https://api.mojang.com/users/profiles/minecraft/MamFuu
`{"name":"MamFuu","id":"e84c63f559784ef38c32e8ac67e27f50"}`

**Comment by McLive** [comment]
Sorry, I found the issue, fixed it and cleared all caches. It should work again now.

**Comment by xhmr** [comment]
> Sorry, I found the issue, fixed it and cleared all caches. It should work again now.

did you cache response when mojang was down or something?

**Comment by McLive** [comment]
> > Sorry, I found the issue, fixed it and cleared all caches. It should work again now.
> 
> did you cache response when mojang was down or something?

Yes, with a shorter cache time, tho.

**Comment by xhmr** [comment]
@McLive how to check if there was an error and if it's offline player?

**Comment by McLive** [comment]
If it's an offline player you'll get the status "ERR" and null UUID.

I'm planning a new "/v2/" API route with better error handling tho.

**Comment by xhmr** [comment]
> If it's an offline player you'll get the status "ERR" and null UUID.
> 
> I'm planning a new "/v2/" API route with better error handling tho.

Yes, but some players had id null and status err.

**Comment by McLive** [comment]
> > If it's an offline player you'll get the status "ERR" and null UUID.
> > I'm planning a new "/v2/" API route with better error handling tho.
> 
> Yes, but some players had id null and status err.

Yeah that was an issue on my backend. There was a service that stopped working.

**Comment by xhmr** [comment]
@McLive so will this happen again? I have to check original mojang link in case of error/null?

**Comment by McLive** [comment]
I don't know, it was never meant to happen at all.

That's why I plan a new API endpoint with better error handling so one can see if that error was caused by minetools or mojang.

**Comment by xhmr** [comment]
@McLive when will you release "API endpoint with better error handling"?

**Comment by McLive** [comment]
> @McLive when will you release "API endpoint with better error handling"?

I'll probably start working on it next week, so it'll still take some time to finish.

**Comment by xhmr** [comment]
@McLive kind of good news! :)

**Comment by xhmr** [comment]
@McLive any progress?

**Comment by McLive** [comment]
Still WIP

**Comment by xhmr** [comment]
@McLive any news? 🥇

**Comment by andreasdc** [comment]
@McLive I had this problem too, I would love to see the update. 🥇

**Comment by andreasdc** [comment]
@McLive any news?
