### ISSUE TITLE
No information comes out of the server

### ISSUE THREAD

**Issue by ElkinSA-bit** [McLive/api.minetools.eu#34]
I was looking for the information of a server with this API, but that server does not appear and has all the query options activated

What could be happening?

**Comment by McLive** [comment]
Can you send me the IP so I can look into it?

**Comment by ElkinSA-bit** [comment]
The server ip is:

play.moonflex.us

**Comment by McLive** [comment]
Works fine for me.

https://api.minetools.eu/ping/play.moonflex.us
https://api.minetools.eu/query/play.moonflex.us

**Comment by ElkinSA-bit** [comment]
Oh, forgive me, I was putting it with its port and nothing came out, but now how did you give it to me if everything works out for me, thank you very much!
