### ISSUE TITLE
HTTP response code 500 for URL: https://api.minetools.eu/profile/d3700141-1c20-49f0-8978-64888730b295

### ISSUE THREAD

**Issue by 4t8k9x1k** [McLive/api.minetools.eu#35]
Hello, we are blocked by minetools. Is there any way to whitelist us?

**Comment by 4t8k9x1k** [comment]
[https://cdn.revenix.xyz/img/583e742f0da05f5ef307caefcd2839b4.png](url)

**Comment by McLive** [comment]
I don't see why you should be blocked. Looks like a temporary issue. Is it still present?

**Comment by 4t8k9x1k** [comment]
Yes it still is. We found out that the website is not spitting out any information, but for some reason the website is getting an Internal Server Error (500). Can you check the log?

**Comment by McLive** [comment]
I don't see any issues on my end. It also is working fine for me.
![image](https://user-images.githubusercontent.com/5620071/117890208-09501500-b2b5-11eb-91d1-7e2291bdbf85.png)

Please provide more information so I can look into it. For exmaple returned response and headers from those 500 requests

**Comment by xPeyotii** [comment]
We are also having problems with getting blocked for https://api.minetools.eu/profile/. It seems to happen every 2 hours or so and on some days it's worse than others. I'm willing to provide a monthly donation if that is needed to keep up the api. The problem first occurred between April 30th and May 4th and has been on-going since.

**Comment by McLive** [comment]
That's weird. I'll look into it again.

**Comment by McLive** [comment]
I just improved some webserver configurations. Please check and report back if it got any better.

**Comment by xPeyotii** [comment]
> I just improved some webserver configurations. Please check and report back if it got any better.

Thanks! I will report back tomorrow with how it went.

**Comment by derBaron555** [comment]
Hey, no 500 Erros occurred so far. We'll check again and get back to you. Thanks for the help!

**Comment by 4t8k9x1k** [comment]
Hey, no 500 Erros occurred so far. We'll check again and get back to you. Thanks for the help!

**Comment by McLive** [comment]
> Hey, no 500 Erros occurred so far. We'll check again and get back to you. Thanks for the help!

Great, thanks for letting me know

**Comment by xPeyotii** [comment]
> > Hey, no 500 Erros occurred so far. We'll check again and get back to you. Thanks for the help!
> 
> Great, thanks for letting me know

No more problems here either so far. I would like to contribute a donation if that's possible.

**Comment by 4t8k9x1k** [comment]
You can open it in an issue. Of course, 500 errors have occurred.

**Comment by 4t8k9x1k** [comment]
> > > Hey, no 500 Erros occurred so far. We'll check again and get back to you. Thanks for the help!
> > 
> > 
> > Great, thanks for letting me know
> 
> No more problems here either so far. I would like to contribute a donation if that's possible.

You can open it in an issue. Of course, 500 errors have occurred.

**Comment by McLive** [comment]
So there are still 500's? Can you point out a time frame when it happened?

**Comment by 4t8k9x1k** [comment]
No 500 have occurred so far. We keep you up to date

**Comment by McLive** [comment]
👍
