### ISSUE TITLE
Firewall unblocking time?

### ISSUE THREAD

**Issue by Nazerillo** [McLive/api.minetools.eu#38]
I've recently had a bot attack in my server that I couldn't stop properly at beggining. So I got banned from mojang and this api for excess the requests. How much time for unblocking I need to wait? Do I need to stop requests some time? (IP: 145.239.130.109)

**Comment by McLive** [comment]
I don’t really ban anyone for sending too many requests.
What response are you getting while using this api?

**Comment by Nazerillo** [comment]
Ok thanks for the answer. After you said you don't block automatically I found it was problem at my firewall. It was a connection refused error and I didn't see it before. Sorry for the inconvenience. I already fixed it.
