### ISSUE TITLE
api.minetools.eu appears to be down

### ISSUE THREAD

**Issue by BitWizrd-Dev** [McLive/api.minetools.eu#4]
The api.minetools.eu site appears to be down, and all queries aren't responding anymore.

**Comment by McLive** [comment]
Yeah I'm aware of that issue. 

Sadly, my domain provider didn't renew the domain after 1 year.
I'm working on getting it up again as soon as possible.

**Comment by McLive** [comment]
It is now stable again since a few days. :)
