### ISSUE TITLE
CORS Question

### ISSUE THREAD

**Issue by Jordan9232** [McLive/api.minetools.eu#41]
Just a question, how did you manage to get around the CORS errors? I tried to use their API before and got the errors and thought it was an issue on their end so I've looked online everywhere I could find and even on the official minecraft issue tracker and one of the devs responded that it is working as intended. Their documentation has absolutely no mention of how to properly get around it. 

I've resorted to using this for a while but I now realize that for what I'm doing I would love to have my login integrated with minecraft accounts so they just login/register using the same credentials.

**Comment by LukeOnuke** [comment]
CORS is a client side restriction embedded into browsers, but for example Java (the og one running on the JVM) doesnt care about cors.
