### ISSUE TITLE
Not all usernames work?

### ISSUE THREAD

**Issue by Leuchtkeks-ctrl** [McLive/api.minetools.eu#44]
Hey,
im writing a Plugin for Bungeecord and noticed, that not all usernames worked with this api.... why is that?

Example:
https://api.minetools.eu/uuid/jeb_ get me the code:
{
  "cache": {
    "HIT": true, 
    "cache_time": 86400, 
    "cache_time_left": 85701, 
    "cached_at": 1670344753.874057, 
    "cached_until": 1670431153.874057
  }, 
  "id": "853c80ef3c3749fdaa49938b674adae6", 
  "name": "jeb_", 
  "status": "OK"
}
But https://api.minetools.eu/uuid/Leuchtkeks (my own username) get me:
{
  "cache": {
    "HIT": true, 
    "cache_time": 86400, 
    "cache_time_left": 9356, 
    "cached_at": 1670268666.260636, 
    "cached_until": 1670355066.260636
  }, 
  "id": null, 
  "name": "Leuchtkeks", 
  "status": "ERR"
}

Can you help me?

Thanks in advance

**Comment by McLive** [comment]
I think Mojang changed the ratelimits again, but tbh this API is no longer in active development. Better switch to another one.

**Comment by Leuchtkeks-ctrl** [comment]
> I think Mojang changed the ratelimits again, but tbh this API is no longer in active development. Better switch to another one.

Oh ok, thy for the information.

Sadly i tried every single api that i could fin on the internet and yours was the best working :(
