### ISSUE TITLE
Favicon error yields to 200 OK?

### ISSUE THREAD

**Issue by jens1o** [McLive/api.minetools.eu#5]
After visiting https://api.minetools.eu/favicon/rewinside.tv you see an error message, but it is still 200 OK and it isn't an image, too...

Are you able to fix this?

**Comment by McLive** [comment]
That's weird! I'll look into this in a few days. 

Thanks for reporting that issue

**Comment by McLive** [comment]
@jens1o I totally forgot to close this issue. There was an issue where the app didn't resolve SRV records for the **/favicon/{ip}** endpoint.

**Comment by jens1o** [comment]
Thank you!
