### ISSUE TITLE
"error": "'str' object has no attribute 'decode'"

### ISSUE THREAD

**Issue by JPNARF** [McLive/api.minetools.eu#52]
Hi,
I received the message:

"error": "'str' object has no attribute 'decode'"

Use to work fine in the past (I checked yesterday)

**Comment by EinEisbxr** [comment]
Same problem here.

**Comment by McLive** [comment]
Thanks for letting me know, this issue came around after migration from python2 to python3.

It should be fixed now.

**Comment by JPNARF** [comment]
Hi, new error:

You can't write against a read only replica.

https://api.minetools.eu/ping/mc.argentospvp.net.ar/25565
