### ISSUE TITLE
TypeError [500]

### ISSUE THREAD

**Issue by PatryQHyper** [McLive/api.minetools.eu#53]
Visit https://api.minetools.eu/ping/anarchia.gg

Most servers return this error

**Comment by McLive** [comment]
This has been fixed for a while.

**Comment by PatryQHyper** [comment]
I would not said that was fixed for a while, because yesterday this errors still occurred

**Comment by McLive** [comment]
Could you try again? At least today another fix was applied

**Comment by PatryQHyper** [comment]
For now, it seems working. I will let u know if it will happen

**Comment by McLive** [comment]
Thanks a lot! 👍
