### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by whiteonred** [McLive/api.minetools.eu#56]
https://api.minetools.eu/query/
....
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 369445049

Varnish cache server

**Comment by Cyanoure** [comment]
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 377708202

Varnish cache server

**Comment by ADG0707** [comment]
YEa this is on my Website too

**Comment by whiteonred** [comment]
Hello, the problem has recurred...

**Comment by JPNARF** [comment]
Yes.. same error here

**Comment by SamGamerYT** [comment]
Same problem

**Comment by kacboy** [comment]
Same here :(

**Comment by McLive** [comment]
I just added more resources to the backend VM, situation should be a lot better now.
