### ISSUE TITLE
Your rate-limit (i would like to query several names at once)

### ISSUE THREAD

**Issue by OmicronZed** [McLive/api.minetools.eu#58]
Hey McLive,

first of all, great service you have there.

I would like to query player names for a dashboard (team-internal). But I need to query several names. There may be 10 names at the same time and the next names are loaded when scrolling through the pages.

Is there a rate-limit on your side? If so, what does the error message look like if there are too many requests? And what is the rate limit?

Best regards :)

**Comment by McLive** [comment]
There currently is no rate-limit implemented. 10 at the same time should be no problem at all.
