### ISSUE TITLE
What happens on rate-limit?

### ISSUE THREAD

**Issue by TuxCoding** [McLive/api.minetools.eu#6]
On your website you wrote:
>Because we use several different mojang proxy-backends, we are able to serve lots of requests hitting the uuid and profile endpoint.

But what happens if you actually hit the rate-limit. Do you we get the 429 response a different json message or something else?

Furthermore how long are the UUIDs cached?

**Comment by McLive** [comment]
currently, it just responds with 200 but with

```
{
  "status": "ERR"
}
```

insted of

```
{
  "status": "OK"
}
```

I plan to add better error handling soon.

Currently, name-> uuid requests are cached 12 hours and uuid -> profile 30 mins.

These times may vary tho. (They are also included in the response).

```
"cache": {
    "HIT": true, 
    "cache_time": 43200, 
    "cached_at": 1518449569.928288, 
    "cached_until": 1518492769.928288
  }, 
```

**Comment by TuxCoding** [comment]
Ok thanks for the info.
