### ISSUE TITLE
I have some problems with it.

### ISSUE THREAD

**Issue by gyucudu** [McLive/api.minetools.eu#8]
If you can, please contact me by email.
because i can't find your email in you github profile.
my email is liangfrank123@outlook.com
thanks a lot.

**Comment by McLive** [comment]
I think it is better to post your issue right here. :)

**Comment by gyucudu** [comment]
Your site provides a lot of useful tools for me.
But your site is seldom known in China
I want to build a site as a mirror site of yours.
Because I want the Chinese developers of Minecraft to request the necessary data more quickly.The speed of your site is not good here.
What do you think of this?

**Comment by CarbonNeuron** [comment]
Unless you could get a faster connection. How would mirroring it help? It would just be the same speed. Unless you are talking about hosting a server yourself like this with the redis backend.
