### ISSUE TITLE
Issues with api?

### ISSUE THREAD

**Issue by ImLunaUwU** [McLive/api.minetools.eu#9]
Okay, so i am trying to get my page to work ([here](https://chromaville.com/status.html)), but everytime it tries to connect, it returns "Server Error (500)". 
This isn't just my server, it is with all. 
Is the api down?

**Comment by ImLunaUwU** [comment]
oh shit, its back. hmm... weird.

**Comment by McLive** [comment]
Hi, it should work again now.

Unfortunately the main backend server just died last night and the fallback backend couldn't keep up with the traffic and also crashed. I'm currently working on getting it stable as always again.

**Comment by ImLunaUwU** [comment]
Yeah its working again! Thanks for getting it back. 👍

**Comment by ImLunaUwU** [comment]
Fixed, closed. :)

**Comment by CarbonNeuron** [comment]
Having another issue with this. Same server error.

**Comment by ImLunaUwU** [comment]
Oh okay. Thanks for letting me know. :)

**Comment by McLive** [comment]
Currently looking into it

**Comment by ImLunaUwU** [comment]
Sounds good
